{
 "title": "MySQL Logs",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Logs Data Source", "query": "loki" },
   { "name": "job", "query": { "query": "label_values(mysql_up, job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs by Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", label=~\".+\"}[$__interval])) by (label)",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Logs by Error Codes",
   "type": "timeseries",
   "description": "Error codes are available in MySQL 8.0 and above.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", err_code!=\"\", label=~\".+\"}[$__interval])) by (label, err_code)",
     "legendFormat": "{{ label }}: {{ err_code }}"
    }
   ]
  },
  {
   "title": "MySQL Errors Log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}