---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.5.0

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.15

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: make check_license style staticcheck unused build test-short
    - prometheus/store_artifact:
        file: mysqld_exporter

  integration:
    machine:
      image: ubuntu-1604:202004-01

    parameters:
      mysql_image:
        type: string

    steps:
    - checkout
    - run: docker version
    - run: docker-compose --version
    - run: make build
    - run:
        name: Run integration test
        command: |
          MYSQL_IMAGE=<< parameters.mysql_image >> docker-compose up -d
          make test

  codespell:
    docker:
    - image: circleci/python

    steps:
    - checkout
    - run: sudo pip install codespell
    - run: codespell --skip=".git,./vendor,ttar,Makefile.common" -L uint,ist,keypair

workflows:
  version: 2
  mysqld_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - integration:
        matrix:
          parameters:
            mysql_image:
            - mysql/mysql-server:5.6
            - mysql/mysql-server:5.7
            - mysql/mysql-server:8.0
            - mariadb:10.1
            - mariadb:10.2
            - mariadb:10.3
            - mariadb:10.4
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - codespell:
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        context: org-context
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
