---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.11.0

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.16

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: make check_license style staticcheck unused build test-short
    - prometheus/store_artifact:
        file: mysqld_exporter

  integration:
    docker:
    - image: circleci/golang:1.16
    - image: << parameters.mysql_image >>
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_HOST: '%'

    parameters:
      mysql_image:
        type: string

    steps:
    - checkout
    - setup_remote_docker
    - run: docker version
    - run: docker-compose --version
    - run: make build
    - run: make test

  codespell:
    docker:
    - image: circleci/python

    steps:
    - checkout
    - run: sudo pip install codespell
    - run: codespell --skip=".git,./vendor,ttar,Makefile.common" -L uint,ist,keypair

  mixin:
    executor: golang

    steps:
    - checkout
    - run: go install github.com/monitoring-mixins/mixtool/cmd/mixtool@latest
    - run: go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
    - run: make -C mysqld-mixin lint build

workflows:
  version: 2
  mysqld_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - integration:
        matrix:
          parameters:
            mysql_image:
            - mysql/mysql-server:5.6
            - mysql/mysql-server:5.7.33
            - mysql/mysql-server:8.0
            - mariadb:10.2
            - mariadb:10.3
            - mariadb:10.4
            - mariadb:10.5
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - codespell:
        filters:
          tags:
            only: /.*/
    - mixin:
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        context: org-context
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
