---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.1.0

jobs:
  test:
    # Whenever the Go version is updated here, .travis.yml and .promu.yml
    # should also be updated.
    docker:
    - image: circleci/golang:1.13

    steps:
    - prometheus/setup_environment
    - run: make check_license style staticcheck unused build test-short
    - prometheus/store_artifact:
        file: mysqld_exporter

  codespell:
    docker:
    - image: circleci/python

    steps:
    - checkout
    - run: sudo pip install codespell
    - run: codespell --skip=".git,./vendor,ttar,Makefile.common" -L uint,ist

workflows:
  version: 2
  mysqld_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - codespell:
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        context: org-context
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
